<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="PrivecyPolicyaspx.aspx.cs" Inherits="PrivecyPolicyaspx" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <div class="container">
        <div class="product-item_price font-additional font-weight-normal customColor"><h2>PRIVACY POLICY</h2></div>
         <p class="customColor"><b>Type of Information Collected: </b></p>
         <p style="text-align:justify">
          When you visit the Website, we may collect certain non-personal information such as your Internet Protocol ("IP") address, operating system, browser type, and Internet service provider. This type of information does not identify you personally. When you register with the Website or respond to advertisements or posts on the Website or post contents on the Website without registering, we may also collect personal information that you provide such as your name, mailing address, email address, phone/mobile number, home country, and zip code ("Registration Information"). You have the option of also providing to us your fax numbers, gender, age, and/or company name if you choose to register with Tausch The Things. If you provide your phone number, it will be displayed in your posting. Further, if you have provided your phone number and posted an advertisement using your account, you agree to receive communications on the provided phone number from our side which may include but not be limited to automated calls or text messages. The communication may require you to confirm and verify that your account has been used to post the relevant advertisement on the Website. We may also collect additional information that our users provide, such as new or deleted postings, new or deleted comments, keyword searches, scam reports and new contact sellers. We use a third-party credit card processing company for purchases, and other third party companies to monitor site traffic, which may, in some instances, store your information. By using this Website or the Service, you consent to collection, storage, and use of the personal information you provide for any of the services that we offer, and you consent to our collection of any changes or updates that you may provide to any information you provide that is collected by Tausch The Things.
         </p>
         <p class="customColor"><b>Cookies</b></p>
          <p style="text-align:justify">
          We may use cookies to manage our users’ sessions and to store preferences, tracking information, and language selection. Cookies may be used whether you register with us or not. "Cookies" are small text files transferred by a web server to your hard drive and thereafter stored on your computer. The types of information a cookie collects include the date and time you visited, your browsing history, your preferences, and your username. In some instances, our third-party service providers may use cookies on the Website. We cannot control or access cookies used by third- party service providers. This Privacy Policy covers only Cookies used by us, and not any cookies used by third parties. You have the ability to either accept or decline the use of cookies on your computer, whether you are registered with us or not. Typically, you can configure your browser to not accept cookies. However, declining the use of cookies may limit your access to certain features of the Website. For example, you may have difficulty logging in or using certain interactive features of the Website.
         </p>
   </div>
</asp:Content>

