<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/admin.master" AutoEventWireup="true" CodeFile="Category.aspx.cs" Inherits="Admin_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
     <form id="form1" runat="server">
    <div style="margin: 0px 0px 0px 85px;">
        <h4 style="font-family: sans-serif; font-size: 20px; font-weight: 300; margin: 25px 0px 30px 30px">Category Management</h4>

        <div class="container">
            
           
                <div style="margin-bottom: 10px;">
                    <div class="row">
                        <div class="col-sm-4">
                            <asp:TextBox ID="txtsearch" CssClass="col-sm-4" runat="server" Height="30px" Width="375px" OnTextChanged="txtsearch_TextChanged"></asp:TextBox>
                        </div>

                        <div class="col-sm-4">
                            <input type="submit" id="btSubmit" class="btn" name="Search" style="background-color:#EAF2Fc" runat="server" />
                        
                            <asp:Button ID="btnshowall" runat="server" CssClass="btn" Text="Show All" BackColor="#EAF2FC" OnClick="btnshowall_Click" />
                            <asp:CheckBox ID="chkadd" runat="server" AutoPostBack="true" OnCheckedChanged="chkadd_CheckedChanged" Text="Insert" />
                        </div>
                        <div class="col-sm-4">
                            <asp:Label ID="msg" runat="server"></asp:Label>
                        </div>
                    </div>


                    <asp:Panel ID="pnlinsert" runat="server" Visible="false">
                        <div class="form-register-with-email">
                            <div class="form-white-background" style="margin-bottom: 20px; padding: 10px 10px;">
                                <div class="form-row">
                                    <label>
                                        <span>Name:</span>
                                        <asp:TextBox ID="Name" runat="server" placeholder="Category Name"></asp:TextBox>

                                    </label>
                                </div>
                                <div class="form-row">
                                    <label>
                                        <span>Description:</span>
                                        <asp:TextBox ID="Description" runat="server" placeholder="Write your description" Height="61px"></asp:TextBox>
                                    </label>
                                </div>


                                <asp:Button ID="Insert" runat="server" Text="Insert" CssClass="btn" BackColor="#EAF2FC" OnClick="Insert_Click" />
                                &nbsp;&nbsp;&nbsp;
                                 <asp:Button ID="Button2" runat="server" Text="Reset" OnClick="Button2_Click" CssClass=" btn btn-default" BackColor="#EDF5FC" />
                                <asp:Label ID="lblmsg" runat="server"></asp:Label>

                            </div>
                        </div>
                    </asp:Panel>
                </div>


                <div class="row" style="margin-bottom: 10px">
                    <asp:GridView ID="GridView1" CssClass="footable" runat="server" OnRowCreated="GridView1_RowCreated" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CatId" DataSourceID="SqlDataSource1" AllowPaging="True" Width="815px">
                        <Columns>

                            <asp:BoundField DataField="CatId" HeaderText="Id" ReadOnly="True" SortExpression="CatId" />
                            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                            <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:SwapshopConnectionString %>" DeleteCommand="DELETE FROM [Category] WHERE [CatId] = @original_CatId AND [Name] = @original_Name AND [Description] = @original_Description" InsertCommand="INSERT INTO [Category] ([CatId], [Name], [Description]) VALUES (@CatId, @Name, @Description)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Category]" UpdateCommand="UPDATE [Category] SET [Name] = @Name, [Description] = @Description WHERE [CatId] = @original_CatId AND [Name] = @original_Name AND [Description] = @original_Description" OnSelecting="SqlDataSource1_Selecting" FilterExpression="[Name] LIKE '%{0}%' or [Description] LIKE '%{1}%'">
                        <DeleteParameters>
                            <asp:Parameter Name="original_CatId" Type="Int32" />
                            <asp:Parameter Name="original_Name" Type="String" />
                            <asp:Parameter Name="original_Description" Type="String" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="CatId" Type="Int32" />
                            <asp:Parameter Name="Name" Type="String" />
                            <asp:Parameter Name="Description" Type="String" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="Name" Type="String" />
                            <asp:Parameter Name="Description" Type="String" />
                            <asp:Parameter Name="original_CatId" Type="Int32" />
                            <asp:Parameter Name="original_Name" Type="String" />
                            <asp:Parameter Name="original_Description" Type="String" />
                        </UpdateParameters>

                        <FilterParameters>
                            <asp:ControlParameter Name="Name"
                                ControlID="txtsearch" PropertyName="Text" />
                            <asp:ControlParameter Name="Description" ControlID="txtsearch" PropertyName="text" />
                        </FilterParameters>
                    </asp:SqlDataSource>

                </div>


                    </ContentTemplate>
                </asp:UpdatePanel>
        </div>
    </div>


         
            </form>


</asp:Content>


